version: "3.8"

services:
  db:
    image: mysql:latest
    ports:
      - 3308:3306
    restart: always
    environment:
      - MYSQL_DATABASE=spootify
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local
