version: "3.8"

services:
  db:
    image: mysql:latest
    ports:
      - 3308:3306
    restart: always
    environment:
      - MYSQL_DATABASE=spootify
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - db:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis:/data

volumes:
  db:
    driver: local
  redis:
    driver: local
