version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3308:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - /data/mysql:/data/mysql